#!/bin/bash
#PBS -N chr05_g2v
#PBS -l nodes=1:ppn=1
#PBS -l walltime=480:00:030
#PBS -e errlog_chr05_g2v
#PBS -q high

cd $PBS_O_WORKDIR

perl gt_to_vcf_for_beagle.pl chr05_4k.txt
awk '{if ($4==0){print;}}' chr05_4k.txt_per >chr05_tmp
awk '{if ($5<0.06){print;}}' chr05_tmp >chr05_tmp2
awk '{if($3>0){print;}}' chr05_tmp2 > chr05_tmp3
cut -f 1 chr05_tmp3 > chr05.list
cp chr05_4k.txt_out chr05_out
perl vcf_get.pl chr05
awk '{if (length($4)==1){print;}}' chr05_snp.vcf > chr05_tmp1
awk '{if (length($5)==1){print;}}' chr05_tmp1 >chr05_snp.vcf
cut -f 2 chr05_snp.vcf > chr05_list
awk '{print "Chr1",$1}' chr05_list > chr05.list
rm chr05_tmp*
rm chr05_list
rm chr05_g2v.o*
rm chr05_out
rm errlog_chr05_g2v
qsub chr05_beagle_ref.pbs
