#!/bin/bash
#PBS -N chr06_g2v
#PBS -l nodes=1:ppn=1
#PBS -l walltime=480:00:030
#PBS -e errlog_chr06_g2v
#PBS -q high

cd $PBS_O_WORKDIR

perl gt_to_vcf_for_beagle.pl chr06_4k.txt
awk '{if ($4==0){print;}}' chr06_4k.txt_per >chr06_tmp
awk '{if ($5<0.06){print;}}' chr06_tmp >chr06_tmp2
awk '{if($3>0){print;}}' chr06_tmp2 > chr06_tmp3
cut -f 1 chr06_tmp3 > chr06.list
cp chr06_4k.txt_out chr06_out
perl vcf_get.pl chr06
awk '{if (length($4)==1){print;}}' chr06_snp.vcf > chr06_tmp1
awk '{if (length($5)==1){print;}}' chr06_tmp1 >chr06_snp.vcf
cut -f 2 chr06_snp.vcf > chr06_list
awk '{print "Chr1",$1}' chr06_list > chr06.list
rm chr06_tmp*
rm chr06_list
rm chr06_g2v.o*
rm chr06_out
rm errlog_chr06_g2v
qsub chr06_beagle_ref.pbs
