#!/bin/bash
#PBS -N chr04_g2v
#PBS -l nodes=1:ppn=1
#PBS -l walltime=480:00:030
#PBS -e errlog_chr04_g2v
#PBS -q high

cd $PBS_O_WORKDIR

perl gt_to_vcf_for_beagle.pl chr04_4k.txt
awk '{if ($4==0){print;}}' chr04_4k.txt_per >chr04_tmp
awk '{if ($5<0.06){print;}}' chr04_tmp >chr04_tmp2
awk '{if($3>0){print;}}' chr04_tmp2 > chr04_tmp3
cut -f 1 chr04_tmp3 > chr04.list
cp chr04_4k.txt_out chr04_out
perl vcf_get.pl chr04
awk '{if (length($4)==1){print;}}' chr04_snp.vcf > chr04_tmp1
awk '{if (length($5)==1){print;}}' chr04_tmp1 >chr04_snp.vcf
cut -f 2 chr04_snp.vcf > chr04_list
awk '{print "Chr1",$1}' chr04_list > chr04.list
rm chr04_tmp*
rm chr04_list
rm chr04_g2v.o*
rm chr04_out
rm errlog_chr04_g2v
qsub chr04_beagle_ref.pbs
