#!/bin/bash
#PBS -N chr03_g2v
#PBS -l nodes=1:ppn=1
#PBS -l walltime=480:00:030
#PBS -e errlog_chr03_g2v
#PBS -q high

cd $PBS_O_WORKDIR

perl gt_to_vcf_for_beagle.pl chr03_4k.txt
awk '{if ($4==0){print;}}' chr03_4k.txt_per >chr03_tmp
awk '{if ($5<0.06){print;}}' chr03_tmp >chr03_tmp2
awk '{if($3>0){print;}}' chr03_tmp2 > chr03_tmp3
cut -f 1 chr03_tmp3 > chr03.list
cp chr03_4k.txt_out chr03_out
perl vcf_get.pl chr03
awk '{if (length($4)==1){print;}}' chr03_snp.vcf > chr03_tmp1
awk '{if (length($5)==1){print;}}' chr03_tmp1 >chr03_snp.vcf
cut -f 2 chr03_snp.vcf > chr03_list
awk '{print "Chr1",$1}' chr03_list > chr03.list
rm chr03_tmp*
rm chr03_list
rm chr03_g2v.o*
rm chr03_out
rm errlog_chr03_g2v
qsub chr03_beagle_ref.pbs
