#!/bin/bash
#PBS -N chr08_g2v
#PBS -l nodes=1:ppn=1
#PBS -l walltime=480:00:030
#PBS -e errlog_chr08_g2v
#PBS -q high

cd $PBS_O_WORKDIR

perl gt_to_vcf_for_beagle.pl chr08_4k.txt
awk '{if ($4==0){print;}}' chr08_4k.txt_per >chr08_tmp
awk '{if ($5<0.06){print;}}' chr08_tmp >chr08_tmp2
awk '{if($3>0){print;}}' chr08_tmp2 > chr08_tmp3
cut -f 1 chr08_tmp3 > chr08.list
cp chr08_4k.txt_out chr08_out
perl vcf_get.pl chr08
awk '{if (length($4)==1){print;}}' chr08_snp.vcf > chr08_tmp1
awk '{if (length($5)==1){print;}}' chr08_tmp1 >chr08_snp.vcf
cut -f 2 chr08_snp.vcf > chr08_list
awk '{print "Chr1",$1}' chr08_list > chr08.list
rm chr08_tmp*
rm chr08_list
rm chr08_g2v.o*
rm chr08_out
rm errlog_chr08_g2v
qsub chr08_beagle_ref.pbs
