#!/bin/bash
#PBS -N chr09_g2v
#PBS -l nodes=1:ppn=1
#PBS -l walltime=480:00:030
#PBS -e errlog_chr09_g2v
#PBS -q high

cd $PBS_O_WORKDIR

perl gt_to_vcf_for_beagle.pl chr09_4k.txt
awk '{if ($4==0){print;}}' chr09_4k.txt_per >chr09_tmp
awk '{if ($5<0.06){print;}}' chr09_tmp >chr09_tmp2
awk '{if($3>0){print;}}' chr09_tmp2 > chr09_tmp3
cut -f 1 chr09_tmp3 > chr09.list
cp chr09_4k.txt_out chr09_out
perl vcf_get.pl chr09
awk '{if (length($4)==1){print;}}' chr09_snp.vcf > chr09_tmp1
awk '{if (length($5)==1){print;}}' chr09_tmp1 >chr09_snp.vcf
cut -f 2 chr09_snp.vcf > chr09_list
awk '{print "Chr1",$1}' chr09_list > chr09.list
rm chr09_tmp*
rm chr09_list
rm chr09_g2v.o*
rm chr09_out
rm errlog_chr09_g2v
qsub chr09_beagle_ref.pbs
