#!/bin/bash
#PBS -N chr01_g2v
#PBS -l nodes=1:ppn=1
#PBS -l walltime=480:00:030
#PBS -e errlog_chr01_g2v
#PBS -q high

cd $PBS_O_WORKDIR

perl gt_to_vcf_for_beagle.pl chr01_4k.txt
awk '{if ($4==0){print;}}' chr01_4k.txt_per >chr01_tmp
awk '{if ($5<0.06){print;}}' chr01_tmp >chr01_tmp2
awk '{if($3>0){print;}}' chr01_tmp2 > chr01_tmp3
cut -f 1 chr01_tmp3 > chr01.list
cp chr01_4k.txt_out chr01_out
perl vcf_get.pl chr01
awk '{if (length($4)==1){print;}}' chr01_snp.vcf > chr01_tmp1
awk '{if (length($5)==1){print;}}' chr01_tmp1 >chr01_snp.vcf
cut -f 2 chr01_snp.vcf > chr01_list
awk '{print "Chr1",$1}' chr01_list > chr01.list
rm chr01_tmp*
rm chr01_list
rm chr01_g2v.o*
rm chr01_out
rm errlog_chr01_g2v
qsub chr01_beagle_ref.pbs
