#!/bin/bash
#PBS -N chr12_g2v
#PBS -l nodes=1:ppn=1
#PBS -l walltime=480:00:030
#PBS -e errlog_chr12_g2v
#PBS -q high

cd $PBS_O_WORKDIR

perl gt_to_vcf_for_beagle.pl chr12_4k.txt
awk '{if ($4==0){print;}}' chr12_4k.txt_per >chr12_tmp
awk '{if ($5<0.06){print;}}' chr12_tmp >chr12_tmp2
awk '{if($3>0){print;}}' chr12_tmp2 > chr12_tmp3
cut -f 1 chr12_tmp3 > chr12.list
cp chr12_4k.txt_out chr12_out
perl vcf_get.pl chr12
awk '{if (length($4)==1){print;}}' chr12_snp.vcf > chr12_tmp1
awk '{if (length($5)==1){print;}}' chr12_tmp1 >chr12_snp.vcf
cut -f 2 chr12_snp.vcf > chr12_list
awk '{print "Chr1",$1}' chr12_list > chr12.list
rm chr12_tmp*
rm chr12_list
rm chr12_g2v.o*
rm chr12_out
rm errlog_chr12_g2v
qsub chr12_beagle_ref.pbs
